# Generated by Django 5.2 on 2025-04-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodio',
            name='reservada_hasta',
        ),
    ]
