# Generated by Django 5.2 on 2025-04-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_episodio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodio',
            name='disponible',
        ),
    ]
